#!/bin/bash
BASEKEY=$1

KEYS=`etcdctl ls --recursive ${BASEKEY} 2>/dev/null`

if [ $? -ne 0 ]; then
  echo "WARNING: No key '${BASEKEY}' found, exiting" 1>&2
  exit 0
fi

for KEY in ${KEYS}; do
  echo `basename ${KEY}`=`etcdctl get ${KEY}`
done
